/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ch09;

import java.awt.Rectangle;
import java.util.Vector;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author wei__chao
 */
public class FrmBorrowQuery1 extends javax.swing.JFrame {
    Vector data;
    Vector title;
    //带滚动条的面板
    JScrollPane scp=new JScrollPane();
    //表格模式
    DefaultTableModel dtm=new DefaultTableModel();
    //表格
    JTable tbl=new JTable(dtm);
    /**
     * Creates new form FrmBorrowQuery1
     */
    public FrmBorrowQuery1() {
        initComponents();
        data=DBCon.queryVectorData("Select * from Borrow");
        title=new Vector();
        //准备表头
        title.add("借阅编号");
        title.add("图书编号");
        title.add("读者编号");
        title.add("借阅时间");
        title.add("还书时间");
        title.add("备注");

        //放置表格到滚动面板上
        scp.setViewportView(tbl);
        
        //设置位置和大小
        scp.setBounds(new Rectangle(10,180,350,170));
        this.getContentPane().add(scp);
        showTableData();
    }
    public void showTableData(){
        //利用表格模式显示数据
        dtm.setDataVector(data, title);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBorrowID = new javax.swing.JLabel();
        txtBorrowID = new javax.swing.JTextField();
        lblBookID = new javax.swing.JLabel();
        txtBookID = new javax.swing.JTextField();
        lblReaderID = new javax.swing.JLabel();
        txtReaderID = new javax.swing.JTextField();
        lblMemo = new javax.swing.JLabel();
        txtMemo = new javax.swing.JTextField();
        lblBorrowDate1 = new javax.swing.JLabel();
        txtBorrowDate1 = new javax.swing.JTextField();
        lblBorrowDate2 = new javax.swing.JLabel();
        txtBorrowDate2 = new javax.swing.JTextField();
        lblReturnDate1 = new javax.swing.JLabel();
        txtReturnDate1 = new javax.swing.JTextField();
        lblReturnDate2 = new javax.swing.JLabel();
        txtReturnDate2 = new javax.swing.JTextField();
        btnQuery = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("借阅信息查询");

        lblBorrowID.setText("借书编号");

        lblBookID.setText("图书编号");

        lblReaderID.setText("读者编号");

        lblMemo.setText("备    注");

        lblBorrowDate1.setText("借书时间");

        lblBorrowDate2.setText(" 至");

        lblReturnDate1.setText("还书时间");

        lblReturnDate2.setText("至");

        btnQuery.setText("查询");
        btnQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnQuery)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblReturnDate1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtReturnDate1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBorrowDate1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBorrowDate1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblReaderID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtReaderID))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBorrowID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBorrowID, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBookID)
                            .addComponent(lblMemo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblReturnDate2)
                                .addComponent(lblBorrowDate2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBorrowDate2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(txtMemo)
                            .addComponent(txtBookID)
                            .addComponent(txtReturnDate2))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBorrowID)
                    .addComponent(txtBorrowID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBookID)
                    .addComponent(txtBookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblReaderID)
                        .addComponent(txtReaderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMemo))
                    .addComponent(txtMemo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBorrowDate1)
                        .addComponent(txtBorrowDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBorrowDate2))
                    .addComponent(txtBorrowDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblReturnDate1)
                        .addComponent(txtReturnDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblReturnDate2))
                    .addComponent(txtReturnDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuery)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryActionPerformed
        //获得用户设置的查询条件
        String BorrowID=txtBorrowID.getText();
        String BookID=txtBookID.getText();
        String ReaderID=txtReaderID.getText();
        String BorrowDate1=txtBorrowDate1.getText();
        String BorrowDate2=txtBorrowDate2.getText();
        String ReturnDate1=txtReturnDate1.getText();
        String ReturnDate2=txtReturnDate2.getText();
        String Memo=txtMemo.getText();

        //SQL语句
        String sql="Select * from Borrow";
        String query="";
        if(BorrowID.length()>0){
            query="BorrowID like '%"+BorrowID+"%'";
        }
        if(BookID.length()>0){
            if(query.length()>0)
            query=query+ "and BookID like '%"+BookID+"%'";
            else
            query="BookID like '%"+BookID+"%'";
        }
        if(ReaderID.length()>0){
            if(query.length()>0)
            query=query+ "and ReaderID like '%"+ReaderID+"%'";
            else
            query="ReaderID like '%"+ReaderID+"%'";
        }
        if(Memo.length()>0){
            if(query.length()>0)
            query=query+ "and Memo like '%"+Memo+"%'";
            else
            query="Memo like '%"+Memo+"%'";
        }
        if(BorrowDate1.length()>0 && BorrowDate2.length()==0){
            if(query.length()>0)
            query=query+"and BorrowDate>='"+BorrowDate1+"'";
            else
            query="BorrowDate>='"+BorrowDate1+"'";
        }else if(BorrowDate1.length()==0 && BorrowDate2.length()>0){
            if(query.length()>0)
            query=query+"and BorrowDate<='"+BorrowDate2+"'";
            else
            query="BorrowDate<='"+BorrowDate2+"'";
        }else if(BorrowDate1.length()>0 && BorrowDate2.length()>0){
            if(query.length()>0)
            query=query+"and BorrowDate>='"+BorrowDate1+"' and BorrowDate<='"+BorrowDate2+"'";
            else
            query="BorrowDate>='"+BorrowDate1+"' and BorrowDate<='"+BorrowDate2+"'";
        }
        if(ReturnDate1.length()>0 && ReturnDate2.length()==0){
            if(query.length()>0)
            query=query+"and ReturnDate>='"+ReturnDate1+"'";
            else
            query="ReturnDate>='"+ReturnDate1+"'";
        }else if(ReturnDate1.length()==0 && ReturnDate2.length()>0){
            if(query.length()>0)
            query=query+"and ReturnDate<='"+ReturnDate2+"'";
            else
            query="ReturnDate<='"+ReturnDate2+"'";
        }else if(ReturnDate1.length()>0 && ReturnDate2.length()>0){
            if(query.length()>0)
            query=query+"and ReturnDate>='"+ReturnDate1+"' and ReturnDate<='"+ReturnDate2+"'";
            else
            query="ReturnDate>='"+ReturnDate1+"' and ReturnDate<='"+ReturnDate2+"'";
        }

        //形成最终的SQL语句
        if(query.length()>0){
            sql=sql+" where "+query;
        }
        System.out.println(sql);
        //执行查询
        data=DBCon.queryVectorData(sql);
        dtm.setDataVector(data, title);
    }//GEN-LAST:event_btnQueryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBorrowQuery1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBorrowQuery1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBorrowQuery1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBorrowQuery1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBorrowQuery1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuery;
    private javax.swing.JLabel lblBookID;
    private javax.swing.JLabel lblBorrowDate1;
    private javax.swing.JLabel lblBorrowDate2;
    private javax.swing.JLabel lblBorrowID;
    private javax.swing.JLabel lblMemo;
    private javax.swing.JLabel lblReaderID;
    private javax.swing.JLabel lblReturnDate1;
    private javax.swing.JLabel lblReturnDate2;
    private javax.swing.JTextField txtBookID;
    private javax.swing.JTextField txtBorrowDate1;
    private javax.swing.JTextField txtBorrowDate2;
    private javax.swing.JTextField txtBorrowID;
    private javax.swing.JTextField txtMemo;
    private javax.swing.JTextField txtReaderID;
    private javax.swing.JTextField txtReturnDate1;
    private javax.swing.JTextField txtReturnDate2;
    // End of variables declaration//GEN-END:variables
}
